### ISSUE TITLE
MLGT-German: concepts have not translated Notes/Examples

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/TMG#7]
All German translations lack translations for Notes/Examples.

**Comment by ReesePlews** [comment]
@ronaldtse these would be considered optional for translation depending on the resources of the MB. since we have already removed untranslated terms, i think these should be left as is because part of the terminology entry has been translated (such as the term, and/or definition).

perhaps on load, the software can compare cells with the matching english cell and then determine if there is a translation or not. that would prevent any untranslated english entries in a non-english language entry from displaying

i will close this for now. if i am misunderstanding something please let me know and re-open.

**Comment by ronaldtse** [comment]
@ReesePlews this issue was meant as a placeholder for the translation to happen. Right now, if DIN experts decide they wanted to help, they probably would like to know what are the priorities in translation...

> perhaps on load, the software can compare cells with the matching english cell and then determine if there is a translation or not. that would prevent any untranslated english entries in a non-english language entry from displaying

This is already implemented:

<img width="1083" alt="Screen Shot 2019-08-14 at 8 52 33 PM" src="https://user-images.githubusercontent.com/11865/63022412-73b40580-bed5-11e9-8027-6e4927900caf.png">

**Comment by ReesePlews** [comment]
@ronaldtse i understand about the "placeholder" idea for registering the issue, but there will be so many changes (superseded, retired, updated, etc) when the new Release is made, at this time the TMG would probably advise the NBs to only help us with maintenance related issues, and not suggest to begin new translations.  the statistics list on the Geolexica site and also on the first page of every information document accompanying the published versions, in my opinion, are enough to show each MB what is outstanding, that is why i am leaning towards not placing that information here as an "active" issue, at least not at this time.  in the future this may change, depending on the level of activity of NBs on github. for now i would like to keep this closed and not create similar issues for other languages. if we need more discussion, let me know and we can talk about it more. thank you
